import json
import os
from datetime import datetime

import asyncpg

from config import DATA_FILE


pool: asyncpg.Pool | None = None


async def init_database():
    global pool

    database_url = os.getenv("DATABASE_URL")
    if database_url:
        pool = await asyncpg.create_pool(database_url)
    else:
        pool = await asyncpg.create_pool(
            host=os.getenv("DB_HOST", "postgres"),
            port=int(os.getenv("DB_PORT", "5432")),
            user=os.getenv("DB_USER", "botuser"),
            password=os.getenv("DB_PASSWORD", "botpassword"),
            database=os.getenv("DB_NAME", "frogbot"),
        )
    print(
        f"Connexion PostgreSQL établie : {os.getenv('DB_HOST', 'postgres')} / "
        f"{os.getenv('DB_NAME', 'frogbot')}"
    )

    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS reminders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT,
            assigned_to BIGINT,
            weekday SMALLINT NOT NULL CHECK (weekday BETWEEN 0 AND 6),
            hour SMALLINT NOT NULL CHECK (hour BETWEEN 0 AND 23),
            minute SMALLINT NOT NULL CHECK (minute BETWEEN 0 AND 59),
            next_run TIMESTAMP NOT NULL
        )
        """
    )

    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS streamers (
            id SERIAL PRIMARY KEY,
            twitch_login TEXT NOT NULL,
            UNIQUE(twitch_login)
        );
        """
    )
    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS migrations (
            name TEXT PRIMARY KEY
        )
        """
    )
    await migrate_json_reminders()


async def migrate_json_reminders():
    if not os.path.exists(DATA_FILE):
        return

    already_migrated = await pool.fetchval(
        "SELECT 1 FROM migrations WHERE name = 'json_reminders'"
    )
    if already_migrated:
        return

    if os.path.getsize(DATA_FILE) == 0:
        await pool.execute(
            "INSERT INTO migrations (name) VALUES ('json_reminders')"
        )
        return

    with open(DATA_FILE, "r", encoding="utf-8") as file:
        reminders = json.load(file)

    async with pool.acquire() as connection:
        async with connection.transaction():
            for reminder in reminders:
                await connection.execute(
                    """
                    INSERT INTO reminders
                        (id, name, description, assigned_to, weekday, hour, minute, next_run)
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                    ON CONFLICT (id) DO NOTHING
                    """,
                    reminder["id"],
                    reminder["name"],
                    reminder.get("description"),
                    reminder.get("assigned_to"),
                    reminder["weekday"],
                    reminder["hour"],
                    reminder["minute"],
                    datetime.strptime(reminder["next_run"], "%Y-%m-%d %H:%M"),
                )
            await connection.execute(
                "SELECT setval(pg_get_serial_sequence('reminders', 'id'), COALESCE(MAX(id), 1), true) FROM reminders"
            )
            await connection.execute(
                "INSERT INTO migrations (name) VALUES ('json_reminders')"
            )


async def get_reminders():
    rows = await pool.fetch("SELECT * FROM reminders ORDER BY next_run")
    return [dict(row) for row in rows]


async def create_reminder(name, description, assigned_to, weekday, hour, minute, next_run):
    reminder = await pool.fetchrow(
        """
        INSERT INTO reminders
            (name, description, assigned_to, weekday, hour, minute, next_run)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING *
        """,
        name,
        description,
        assigned_to,
        weekday,
        hour,
        minute,
        next_run,
    )
    print(f"Rappel #{reminder['id']} enregistré dans PostgreSQL")
    return reminder


async def update_next_run(reminder_id, next_run):
    await pool.execute(
        "UPDATE reminders SET next_run = $1 WHERE id = $2",
        next_run,
        reminder_id,
    )


async def delete_reminder(reminder_id):
    result = await pool.execute("DELETE FROM reminders WHERE id = $1", reminder_id)
    return result == "DELETE 1"

##----STREAMER
async def add_streamer(twitch_login):
    await pool.execute(
        """
        INSERT INTO streamers (twitch_login) VALUES ($1)
        """,
        twitch_login,
    )

async def remove_streamer(twitch_login) -> bool :
    result = await pool.execute(
        "DELETE FROM streamers WHERE twitch_login = $1",
        twitch_login,
    )
    return result == "DELETE 1"

async def get_streamer():
    return await pool.fetch(
        "SELECT * FROM streamers"
    )
