from datetime import datetime
from config import DATA_FILE
import json
import os
import asyncpg



pool: asyncpg.Pool | None = None


async def init_database():
    global pool

    database_url = os.getenv("DATABASE_URL")
    if database_url:
        pool = await asyncpg.create_pool(database_url)
    else:
        pool = await asyncpg.create_pool(
            host=os.getenv("DB_HOST", "postgres"),
            port=int(os.getenv("DB_PORT", "5432")),
            user=os.getenv("DB_USER", "botuser"),
            password=os.getenv("DB_PASSWORD", "botpassword"),
            database=os.getenv("DB_NAME", "frogbot"),
        )
    print(
        f"Connexion PostgreSQL établie : {os.getenv('DB_HOST', 'postgres')} / "
        f"{os.getenv('DB_NAME', 'frogbot')}"
    )

    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS reminders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT,
            assigned_to BIGINT,
            weekday SMALLINT NOT NULL CHECK (weekday BETWEEN 0 AND 6),
            hour SMALLINT NOT NULL CHECK (hour BETWEEN 0 AND 23),
            minute SMALLINT NOT NULL CHECK (minute BETWEEN 0 AND 59),
            next_run TIMESTAMP NOT NULL
        )
        """
    )

    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS streamers (
            id SERIAL PRIMARY KEY,
            twitch_login TEXT NOT NULL,
            UNIQUE(twitch_login)
        );
        """
    )
    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS migrations (
            name TEXT PRIMARY KEY
        )
        """
    )
    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS ingredients (
            id_ingredient SERIAL PRIMARY KEY,
            name TEXT NOT NULL
        )
        """
    )
    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS recipies(
            id_recipie SERIAL PRIMARY KEY,
            name TEXT NOT NULL
        )
        """
    )
    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS menus(
            id_menu SERIAL PRIMARY KEY,
            date_ DATE NOT NULL DEFAULT CURRENT_DATE
        )
        """
    )
    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS include_ingredients(
            id_ingredient INT NOT NULL,
            id_recipie INT NOT NULL,
            count INT NOT NULL DEFAULT 1,
            PRIMARY KEY (id_ingredient, id_recipie),
            FOREIGN KEY (id_ingredient) REFERENCES ingredients(id_ingredient),
            FOREIGN KEY (id_recipie) REFERENCES recipies(id_recipie)
        )
        """
    )

    await pool.execute(
        "ALTER TABLE include_ingredients ADD COLUMN IF NOT EXISTS count INT NOT NULL DEFAULT 1"
    )

    await pool.execute(
        """
        CREATE TABLE IF NOT EXISTS include_recipies(
            id_menu INT NOT NULL,
            id_recipie INT NOT NULL,
            count INT NOT NULL DEFAULT 1,
            PRIMARY KEY (id_menu, id_recipie),
            FOREIGN KEY (id_menu) REFERENCES menus(id_menu),
            FOREIGN KEY (id_recipie) REFERENCES recipies(id_recipie)
        )
        """
    )

    await pool.execute(
        "ALTER TABLE include_recipies ADD COLUMN IF NOT EXISTS count INT NOT NULL DEFAULT 1"
    )

    await migrate_json_reminders()


async def migrate_json_reminders():
    if not os.path.exists(DATA_FILE):
        return

    already_migrated = await pool.fetchval(
        "SELECT 1 FROM migrations WHERE name = 'json_reminders'"
    )
    if already_migrated:
        return

    if os.path.getsize(DATA_FILE) == 0:
        await pool.execute(
            "INSERT INTO migrations (name) VALUES ('json_reminders')"
        )
        return

    with open(DATA_FILE, "r", encoding="utf-8") as file:
        reminders = json.load(file)

    async with pool.acquire() as connection:
        async with connection.transaction():
            for reminder in reminders:
                await connection.execute(
                    """
                    INSERT INTO reminders
                        (id, name, description, assigned_to, weekday, hour, minute, next_run)
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                    ON CONFLICT (id) DO NOTHING
                    """,
                    reminder["id"],
                    reminder["name"],
                    reminder.get("description"),
                    reminder.get("assigned_to"),
                    reminder["weekday"],
                    reminder["hour"],
                    reminder["minute"],
                    datetime.strptime(reminder["next_run"], "%Y-%m-%d %H:%M"),
                )
            await connection.execute(
                "SELECT setval(pg_get_serial_sequence('reminders', 'id'), COALESCE(MAX(id), 1), true) FROM reminders"
            )
            await connection.execute(
                "INSERT INTO migrations (name) VALUES ('json_reminders')"
            )


async def get_reminders():
    rows = await pool.fetch("SELECT * FROM reminders ORDER BY next_run")
    return [dict(row) for row in rows]


async def create_reminder(name, description, assigned_to, weekday, hour, minute, next_run):
    reminder = await pool.fetchrow(
        """
        INSERT INTO reminders
            (name, description, assigned_to, weekday, hour, minute, next_run)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING *
        """,
        name,
        description,
        assigned_to,
        weekday,
        hour,
        minute,
        next_run,
    )
    print(f"Rappel #{reminder['id']} enregistré dans PostgreSQL")
    return reminder


async def update_next_run(reminder_id, next_run):
    await pool.execute(
        "UPDATE reminders SET next_run = $1 WHERE id = $2",
        next_run,
        reminder_id,
    )


async def delete_reminder(reminder_id):
    result = await pool.execute("DELETE FROM reminders WHERE id = $1", reminder_id)
    return result == "DELETE 1"

##----STREAMER
async def add_streamer(twitch_login):
    await pool.execute(
        """
        INSERT INTO streamers (twitch_login) VALUES ($1)
        """,
        twitch_login,
    )

async def remove_streamer(twitch_login) -> bool :
    result = await pool.execute(
        "DELETE FROM streamers WHERE twitch_login = $1",
        twitch_login,
    )
    return result == "DELETE 1"

async def get_streamers():
    return await pool.fetch(
        "SELECT * FROM streamers"
    )

##--------MENU

# ajouter ingrédient -> nom

async def add_ingredient(name) -> bool :
    await pool.execute(
        "INSERT INTO ingredients (name) VALUES ($1)",
        name,
    )
    return True

# ajouter recette -> nom

async def add_recipie(name) -> bool:
    await pool.execute(
        "INSERT INTO recipies (name) VALUES ($1)",
        name,
    )
    return True

# ajouter menu -> retour d'indice + recette

async def add_menu() -> int:
    row = await pool.fetchrow(
        "INSERT INTO menus (date_) VALUES (CURRENT_DATE) RETURNING id_menu",
    )
    return row['id_menu']

#ajouter un ingrédient à une recette

async def add_ingredient_to_recipie(count: int, ingredient: str, recipie: str) -> bool:
    await pool.execute(
        """
        INSERT INTO include_ingredients (id_ingredient, id_recipie, count) VALUES (
            (SELECT id_ingredient FROM ingredients WHERE name LIKE $1),
            (SELECT id_recipie FROM recipies WHERE name LIKE $2),
            $3
        )
        ON CONFLICT DO NOTHING;
        """,
        ingredient, recipie, count
    )
    return True

async def debug_tables():
    ings = await pool.fetch("SELECT id_ingredient, name FROM ingredients")
    recs = await pool.fetch("SELECT id_recipie, name FROM recipies")
    print("--- INGREDIENTS ---")
    for r in ings:
        print(r['id_ingredient'], repr(r['name']))
    print("--- RECETTES ---")
    for r in recs:
        print(r['id_recipie'], repr(r['name']))

#ajouter recette à un menu

async def add_recipie_to_menu(count: int, id_menu: int, recipie: str) -> bool:
    await pool.execute(
        """
        INSERT INTO include_recipies (id_recipie, id_menu, count) VALUES (
            (SELECT id_recipie FROM recipies WHERE name LIKE $1),
            $2,
            $3
        )
        ON CONFLICT DO NOTHING;
        """,
        recipie, id_menu, count
    )
    return True

#liste des ingrédients

async def get_ingredients():
    return await pool.fetch(
        "SELECT * FROM ingredients"
    )

#liste des recettes

async def get_recipies():
    return await pool.fetch(
        "SELECT * FROM recipies"
    )

#liste des menus

async def get_menus():
    return await pool.fetch(
        "SELECT * FROM menus"
    )

#afficher une recette

async def get_recipie(name: str):
    return await pool.fetch(
        """
        SELECT i.name, ii.count
        FROM ingredients i
        JOIN include_ingredients ii ON i.id_ingredient = ii.id_ingredient
        JOIN recipies r ON ii.id_recipie = r.id_recipie
        WHERE r.name LIKE $1
        """,
        name
    )

#afficher un menu

async def get_menu(id: int):
    return await pool.fetch(
        """
        SELECT m.date_, r.name, ir.count
        FROM recipies r
        JOIN include_recipies ir ON r.id_recipie = ir.id_recipie
        JOIN menus m ON m.id_menu = ir.id_menu
        WHERE m.id_menu = $1
        """,
        id
    )

#afficher ingrédients d'un menu


async def get_menu_ingredients(id: int):
    return await pool.fetch(
        """
        SELECT i.name, SUM(ii.count * ir.count) AS total, m.date_
        FROM ingredients i
        JOIN include_ingredients ii ON i.id_ingredient = ii.id_ingredient
        JOIN include_recipies ir ON ii.id_recipie = ir.id_recipie
        JOIN menus m ON ir.id_menu = m.id_menu
        WHERE m.id_menu = $1
        GROUP BY i.name, m.date_
        ORDER BY total DESC
        """,
        id
    )
