services:
  frog-bot:
    build: .
    container_name: frog-bot
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./reminders.json:/app/reminders.json
      - ./cogs:/app/cogs
    restart: unless-stopped